submodules/menu/menu.js

In kazoo/application/callflows/src/module/cf_menu.erl:135 there is defined the Digit "timeout" for defining an action in case of timeout (so timeout is not handled like an invalid entry).
Adding this, will show on the callflow the menu option "timeout" and works correctly.

Timeout branch

---

submodules/featurecodes/featurecodes.js

Mailbox feature code *98 support BLF monitoring WMI of box possibly not associated with the phone. Change to pattern "^\\*98([0-9]*)$'.

Help 29997 Mailbox Feature code support pattern for mailbox number, BLF dial

---

submodules/device/device.js

We usually insert templates using jQuery methods but it is possible to
do it manually by passing them as regular data to another template.

UI-3126: Do not use jQuery wrapper for templates inserted by Handlebars

---

app.js
views/rowNumber.html

Moved number/extension formatting away from the template following the
update of `monster.util.formatPhoneNumber` helper that now format phone
numbers only.

UI-3353: Fix extension formatting on flow rendering

---

submodules/device/device.js

disableAutoFill implements the protectedField behavior, meaning that calling them on the same form breaks the functionality.

MACF-27: Remove usage of protectedField

---

app.js
i18n/en-US.json
submodules/branchvariable/branchvariable.js
submodules/branchvariable/views/callflowEdit.html
submodules/branchvariable/views/callflowKey.html

The goal of this PR is to expose the callflow module [branch_variable](https://docs.2600hz.com/supported/applications/callflow/doc/cf_branch_variable/) through the UI.
As an example, we create a callflow playing a text for inbound calls (with the purpose of being used as a preflow and warn callers they're being recorded):

MACF-44: Add support for branch_variable module

---

app.js
submodules/branchvariable/branchvariable.js

Default to parameterless action entry, if the parameter version is not registered in the available callflow actions, to allow to have a single definition for branchvariable module.

MACF-60: Remove duplicated branch variable action

---

app.js
submodules/branchvariable/branchvariable.js

Default to parameterless action entry, if the parameter version is not registered in the available callflow actions, to allow to have a single definition for branchvariable module.

[5.0] MACF-60: Remove duplicated branch variable action

---

submodules/user/user.js

While implementing PROD-199 (STIR/SHAKEN), one requirement was the ability to toggle the new UX depending on the reachability of its related endpoint (`/external_numbers`).
We then conditionally render that specific UX component based on the presence of data for `/external_numbers`.
This one instance fell through the cracks and was not properly modified to reflect that requirement. I've also double checked every implementation to make sure they were modified correctly.
Behavioral testing can be achieved on the UI by changing the value for `monster.apps.auth.appFlags.capabilities.caller_id.external_numbers.available=true|false` in the console before loading a specific page . When set to `true`, the UI should force end users to select a known CID versus free form selection.

PROD-199: Check for external numbers capability status

---

i18n/en-US.json
submodules/user/views/edit.html

Duplicate call forwarding settings into a failover object (account, user, device) and remove ‘failover’ as a call forward option.
The intend is to allow users to be able to change their call forwarding settings without impacting the failover settings and have failover set independently from forward.

PROD-169: split failover from forward

---

i18n/en-US.json
submodules/user/views/edit.html

Duplicate call forwarding settings into a failover object (account, user, device) and remove ‘failover’ as a call forward option.
The intend is to allow users to be able to change their call forwarding settings without impacting the failover settings and have failover set independently from forward.

[5.1] PROD-169: split failover from forward

---

submodules/timeofday/timeofday.js

changing `dateToEndOfGregorianDay`  to `dateToBeginningOfGregorianDay` and passing `monster.util.getCurrentTimeZone()` ass second parameter to solve the issue of timezone convertions adding or reducing a day from the `time of day` `start date`.

MACF-76: Fix Time Of Day Increment When Saving

---

submodules/timeofday/timeofday.js

changing `dateToEndOfGregorianDay`  to `dateToBeginningOfGregorianDay` and passing `monster.util.getCurrentTimeZone()` ass second parameter to solve the issue of timezone convertions adding or reducing a day from the `time of day` `start date`.

[5.1] MACF-76: Fix Time Of Day Increment When Saving

---

submodules/timeofday/timeofday.js

changing `dateToEndOfGregorianDay`  to `dateToBeginningOfGregorianDay` and passing `monster.util.getCurrentTimeZone()` ass second parameter to solve the issue of timezone convertions adding or reducing a day from the `time of day` `start date`.

[5.2] MACF-76: Fix Time Of Day Increment When Saving

---

i18n/en-US.json
submodules/timeofday/timeofday.js
submodules/timeofday/views/callflowEdit.html

The improvements at the edit page for Time Of Day include the following:
* Display the end date form field, if the value is present.
* Mark the entry as "All day", if no time is specified.
* Disable all the form fields to prevent user input, if the save button is hidden.
* Hide repeat cycle field for non-recurring holidays.

MACF-75: Improve edit view for holidays at Time Of Day

---

i18n/en-US.json
submodules/timeofday/timeofday.js
submodules/timeofday/views/callflowEdit.html

The improvements at the edit page for Time Of Day include the following:
* Display the end date form field, if the value is present.
* Mark the entry as "All day", if no time is specified.
* Disable all the form fields to prevent user input, if the save button is hidden.
* Hide repeat cycle field for non-recurring holidays.

[5.2] MACF-75: Improve edit view for holidays at Time Of Day

---

submodules/device/device.js

https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/devices.md
Key | Description | Type | Default | Required | Support Level 
--- | ----------- | ---- | ------- | -------- | -------------
`sip.ignore_completed_elsewhere` | When set to false the phone should not consider ring group calls answered elsewhere as missed | `boolean()` |   | `false` |

MACF-81: Revert 'UI-2948: set ignore completed elsewhere to true by default'

---

submodules/device/device.js

https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/devices.md
Key | Description | Type | Default | Required | Support Level
--- | ----------- | ---- | ------- | -------- | -------------
`sip.ignore_completed_elsewhere` | When set to false the phone should not consider ring group calls answered elsewhere as missed | `boolean()` |   | `false` |

[5.3] MACF-81: Revert 'UI-2948: set ignore completed elsewhere to true by default

---

app.js

MUDA-18: Show meta device as active

---

submodules/device/device.js

https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/devices.md
Key | Description | Type | Default | Required | Support Level
--- | ----------- | ---- | ------- | -------- | -------------
`sip.ignore_completed_elsewhere` | When set to false the phone should not consider ring group calls answered elsewhere as missed | `boolean()` |   | `false` |

[5.1] MACF-81: Revert 'UI-2948: set ignore completed elsewhere to true by default

---

app.js

If the app assets is loading from external `source_url`, if the app tries to require its sub modules directly it will fail and the app won't load at all.
Changing the module name to its external `source_url` as what Monster UI core was previously doing won't always work in case the sub modules were small enough and optimized away in a single file as `app.js`. This has been observed with `branding` and `call-recording` apps so far.
Instead we can explicitly config the paths for sub module and its external source url for `requirejs` to load it, if it is not already optimized in the `app.js`.
Without this change, because `app.js` is requiring the submodules, this URL will be used instead of external source_url:
```
http://{monster_ui_url}/apps/:appname/submodules/{submodule}/{submodule}.js …
```

[5.3] MSTR-275: do not require sub module, let core handle it
